# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-21 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cercleforme', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseTypes',
            new_name='CourseType',
        ),
    ]
