# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-21 21:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cercleforme', '0002_auto_20170521_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0, 3600)),
        ),
    ]
