# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-21 21:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cercleforme', '0003_course_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='hour',
            new_name='end_time',
        ),
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.AddField(
            model_name='course',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2017, 5, 21, 21, 37, 50, 566423, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
