# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cercleforme', '0005_auto_20170521_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='day',
            field=models.CharField(choices=[('LU', 'Lundi'), ('MA', 'Mardi'), ('ME', 'Mercredi'), ('JE', 'Jeudi'), ('VE', 'Vendredi'), ('SA', 'Samedi'), ('DI', 'Dimanche')], max_length=150),
        ),
    ]
