# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cercleforme', '0006_auto_20170522_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='day',
            field=models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi'), ('Dimanche', 'Dimanche')], max_length=150),
        ),
    ]
